<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Hizkia Frederikh Nainggolan">
<meta name="dcterms.date" content="2023-01-19">

<title>Pengaruh Ekspor Impor Terhadap PDRB Provinsi Jawa Timur 2008-2021</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pengaruh Ekspor Impor Terhadap PDRB Provinsi Jawa Timur 2008-2021</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Hizkia Frederikh Nainggolan </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 19, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p><img src="logoapp.jpeg" class="img-fluid"></p>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Pertumbuhan ekonomi adalah proses meningkatnya kegiatan perekonomian sehingga produksi barang dan jasa bertambah. Menurut Simon Kuznets dalam Todaro (2000) mendefinisikan pertumbuhan ekonomi adalah kenaikan kapasitas dalam jangka panjang dari suatu negara untuk menyediakan berbagai barang ekonomi kepada penduduknya. Tolak ukur kemajuan suatu daerah adalah dengan meningkatnya pertumbuhan ekonomi didaerah tersebut. Meningkatnya pertumbuhan ekonomi dapat dilihat dari jumlah produksi barang dan jasa yang akan meningkatkan pendapatan didaerah tersebut.</p>
<p>Dengan adanya keinginan setiap daerah untuk memiliki pertumbuhan ekonomi yang pesat, maka setiap daerah melakukan kegiatan jual beli dengan daerah lain, salah satunya melalui kegiatan ekspor dan impor yang dilakukan dengan negara lain. Tujuan dari dilakukannya kegiatan ekspor dan impor adalah guna untuk meningkatkan pendapatan daerah tersebut dan juga memenuhi kebutuhan daerah. Adanya kegiatan ekspor (jual) dan impor (beli) didaerah tersebut maka akan memberikan pengaruh terhadap pertumbuhan ekonomi, karena baik ekspor maupun impor keduanya sama-sama memberikan efek dan berperan terhadap kegiatan ekonomi yang akan berpengaruh pada pertumbuhan ekonomi. Menurut Mankiw (2006:76) PDRB adalah nilai pasar semua barang dan jasa akhir yang diproduksi dalam perekonomian selama kurun waktu tertentu. Pertumbuhan ekonomi dapat dilihat dari Produk Domestik Regional Bruto (PDRB), dimana PDRB ini menggambarkan kondisi atau kemampuan suatu daerah dalam mengelola sumber daya untuk menciptakan nilai tambah.</p>
<p>Jawa Timur adalah salah satu provinsi di pulau Jawa yang memiliki sumber daya yang dimanfaatkan untuk dijual atau ekspor, tetapi juga bukan hanya menjual atau mengekspor tetapi juga melakukan kegiatan pembelian atau impor dari negara lain, ditambah lagi dengan jumlah penduduk di provinsi Jawa Timur yang cukup banyak, maka hal ini akan berkaitan dengan kegiatan ekonomi di Jawa Timur. PDRB di Jawa Timur diperoleh dari beberapa lapangan usaha seperti pertanian, pertambangan, industi, administrasi pemerintahan, jasa-jasa, perdagangan, dan lainnya. Kondisi PDRB Jawa Timur dari tahun 2008-2021 selalu mengalami peningkatan, tetapi dalam bidang ekspor dan impor secara keseluruhan tidak selalu mengalami peningkatan atau berada pada kondisi fluktuatif. Sehingga dapat dipastikan adanya faktor lain yang mempengaruhi PDRB Jawa Timur.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Dalam penelitian ini penulis mengambil objek penelitian dari Badan Pusat Statistik Jawa Timur. Ruang lingkup penelitian ini terdapat 3 variabel antara lain nilai ekspor keseluruhan provinsi Jawa Timur, nilai impor keseluruhan Jawa Timur, dan nilai Produk Domestik Regional Bruto Jawa Timur. Data yang digunakan adalah data yang bersifat time series yaitu dalam kurun waktu 2008-2021 dengan satuan yang telah diubah ke dalam USD guna untuk memudahkan penyetaraan mata uang secara internasional, data inilah yang kemudian menjadi objek penelitian.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<p>Berdasarkan uraian latar belakang diatas maka yang menjadi masalah pokok pada penelitian ini adalah:</p>
<ol type="1">
<li>Apakah ekspor dan impor berpengaruh pada PDRB di Jawa Timur?</li>
<li>Bagaimana hubungan ekspor dan impor terhadap peningkatan PDRB di Jawa Timur?</li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Berdasarkan latar belakang dan permasalahan yang ada maka tujuan dari penelitian ini adalah untuk mengetahui pengaruh ekspor dan impor terhadap PDRB Jawa Timur dan mengetahui hubungan ekspor dan impor terhadap peningkatan PDRB Jawa Timur.</p>
<p>Adapun manfaat dari penelitian ini antara lain:</p>
<p>1. Manfaat Teoritis</p>
<p>Penelitian ini diharapkan dapat memberikan bantuan pemikiran dan menjadi ilmu pengetahuan bagi para pembaca untuk menambah wawasan seputar ekonomi.</p>
<p>2. Manfaat Praktis</p>
<p>a. Bagi Penulis</p>
<p>Diharapkan penelitian ini bisa menjadi referensi bagi mereka yang ingin memperdalam tentang kegiatan ekspor, impor, dan pertumbuhan ekonomi, sehingga dengan adanya karya lain secara tidak langsung penelitian ini mengalami penyempurnaan secara terus menerus. Dan diharapkan penelitian ini juga dapat menjadi referensi bagi setiap penulis yang ingin mengetahui penelitian menggunakan sistem regresi melalui R Studio.</p>
<p>b. Bagi instansi</p>
<p>Sebagai bahan masukan dan saran guna untuk memperbaiki sistem perekonomian khususnya di daerah Jawa timur.</p>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Packages yang digunakan sebagai penunjang regresi multivariat dalam penelitian ini antara lain sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(WDI) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<ol type="1">
<li>Ekspor</li>
</ol>
<p>Ekspor adalah kegiatan mengeluarkan barang dari daerah pabean. Menurut Lipsey (1995), ekspor dapat diartikan sebagai total penjualan barang yang dapat dihasilkan oleh suatu negara, kemudian diperdagangkan kepada negara lain dengan tujuan mendapatkan devisa. Suatu negara dapat mengekspor barang-barang yang dihasilkannya ke negara lain yang tidak dapat menghasilkan barang-barang yang dihasilkan negara pengekspor. Menurut Salvatore (1997), terdapat beberapa alasan sehingga dilakukannya ekspor oleh suatu negara, antara lain:</p>
<p>a. Keinginan untuk memenuhi berbagai kebutuhan yang tidak dapat dipenuhi dari produksi atau hasil dalam negeri, termasuk kebutuhan yang dapat diproduksi namun diperlukan biaya yang lebih tinggi dibandingkan jika diproduksi di luar negeri.</p>
<p>b. Keinginan suatu negara untuk memperluas pemasaran komoditas domestik untuk meningkatkan sumber devisa bagi kegiatan pembangunan.</p>
<ol start="2" type="1">
<li>Impor</li>
</ol>
<p>Impor adalah kegiatan memasukan barang ke dalam daerah pabean. Impor bertindak sebaliknya daripada ekspor, saat ekspor dapat meningkatkan pendapatan nasional maka impor dapat menambah pengeluaran dan menurunkan pendapatan nasional suatu daerah. Menurut Sukirno (2011) aliran barang impor dapat menimbulkan aliran keluar atau bocoran dari aliran pengeluaran sektor rumah tangga ke sektor perusahaan yang pada akhirnya menurunkan pendapatan nasional yang mungkin dapat dicapai. Tetapi disatu sisi impor terdapat sisi baiknya yaitu membantu negara memenuhi kebutuhan dalam negeri apabila barang atau jasa yang diimpor tidak ada di negara atau daerah tersebut, hal ini selaras dengan yang dijelaskan dalam teori Hecksher-Ohlin (dalam Appleyeard, Field dan Cobb, 2008) menyatakan bahwa suatu negara akan mengimpor produk/barang yang menggunakan faktor produksi yang tidak atau jarang dimiliki oleh negara tersebut. Kegiatan ini akan menguntungkan bagi negara tersebut dibandingkan melakukan produksi sendiri namun tidak secara efisien.</p>
<ol start="3" type="1">
<li>Pertumbuhan Ekonomi</li>
</ol>
<p>Pertumbuhan ekonomi dapat diartikan sebagai perkembangan kegiatan perekonomian yang menyebabkan barang dan jasa yang dihasilkan masyarakat meningkat (Sukirno, 2012). Salah satu indikator untuk melihat kondisi ekonomi suatu daerah adalah PDRB. PDRB pada dasarnya adalah jumlah nilai tambah yang dihasilkan oleh seluruh unit usaha dalam suatu negara tertentu, atau merupakan jumlah dari nilai barang dan jasa yang diproduksi oleh seluruh unit ekonomi. Sjafrizal (2008), menjelaskan bahwa PDRB merupakan penjumlahan dari konsumsi, investasi, pengeluaran pemerintah, dan ekspor, dikurangi impor.</p>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<p>Berikut adalah data yang digunakan sebagai objek penelitian, data dibawah ini merupakan data nilai ekspor, impor, dan PDRB Provinsi Jawa Timur dengan satuan USD.</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;">Tahun</th>
<th style="text-align: center;">Ekspor (X)</th>
<th style="text-align: center;">Impor (S)</th>
<th style="text-align: center;">PDRB (Y)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">2008</td>
<td style="text-align: center;">10.595.255.387</td>
<td style="text-align: center;">17.846.110.380</td>
<td style="text-align: center;">50.406.934.070,51</td>
</tr>
<tr class="even">
<td style="text-align: center;">2009</td>
<td style="text-align: center;">10.791.937.520</td>
<td style="text-align: center;">11.321.978.983</td>
<td style="text-align: center;">57.132.529.600,35</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2010</td>
<td style="text-align: center;">15.340.476.475</td>
<td style="text-align: center;">15.984.224.882</td>
<td style="text-align: center;">65.337.154.528,48</td>
</tr>
<tr class="even">
<td style="text-align: center;">2011</td>
<td style="text-align: center;">19.062.771.105</td>
<td style="text-align: center;">23.003.767.092</td>
<td style="text-align: center;">73.906.433.952,92</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2012</td>
<td style="text-align: center;">16.249.221.758</td>
<td style="text-align: center;">24.477.248.309</td>
<td style="text-align: center;">82.361.072.967,93</td>
</tr>
<tr class="even">
<td style="text-align: center;">2013</td>
<td style="text-align: center;">15.508.414.141</td>
<td style="text-align: center;">25.046.102.829</td>
<td style="text-align: center;">91.181.365.680,85</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2014</td>
<td style="text-align: center;">1.557.982.463</td>
<td style="text-align: center;">1.975.151.309</td>
<td style="text-align: center;">101.433.644.194,26</td>
</tr>
<tr class="even">
<td style="text-align: center;">2015</td>
<td style="text-align: center;">17.120.185.401</td>
<td style="text-align: center;">19.286.534.433</td>
<td style="text-align: center;">111.559.508.867,53</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2016</td>
<td style="text-align: center;">18.952.202.820</td>
<td style="text-align: center;">18.589.422.450</td>
<td style="text-align: center;">122.393.186.838,38</td>
</tr>
<tr class="even">
<td style="text-align: center;">2017</td>
<td style="text-align: center;">19.613.196.004</td>
<td style="text-align: center;">22.115.653.638</td>
<td style="text-align: center;">132.759.791.820,66</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2018</td>
<td style="text-align: center;">20.393.262.984</td>
<td style="text-align: center;">25.733.627.908</td>
<td style="text-align: center;">144.357.676.971,26</td>
</tr>
<tr class="even">
<td style="text-align: center;">2019</td>
<td style="text-align: center;">20.284.491.411</td>
<td style="text-align: center;">23.335.474.513</td>
<td style="text-align: center;">154.698.074.511,84</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2020</td>
<td style="text-align: center;">19.216.163.872</td>
<td style="text-align: center;">19.985.674.723</td>
<td style="text-align: center;">151.680.188.932,59</td>
</tr>
<tr class="even">
<td style="text-align: center;">2021</td>
<td style="text-align: center;">22.780.677.951</td>
<td style="text-align: center;">27.479.470.825</td>
<td style="text-align: center;">161.883.768.405,32</td>
</tr>
</tbody>
</table>
<p>Penelitian ini menggunakan data sekunder dengan bentuk data <em>time series</em> 2008-2021, data yang dipakai ialah data yang telah diolah dengan sumber Badan Pusat Statistik Jawa Timur.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"C:/Metodologi Penelitian/Tugas UAS"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>Hizkia<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'latihan.xlsx'</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X<span class="sc">+</span>S,<span class="at">data=</span>Hizkia)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>Hizkia<span class="sc">$</span>m<span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Hizkia<span class="sc">$</span>X,Hizkia<span class="sc">$</span>m,<span class="at">xlab=</span><span class="st">"Nilai Ekspor"</span>,<span class="at">ylab=</span><span class="st">"error"</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/Nilai%20Ekspor%20Jawa%20Timur-Error-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Plot pengaruh error terhadap nilai ekspor</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>Hizkia<span class="sc">$</span>m<span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Hizkia<span class="sc">$</span>Y,Hizkia<span class="sc">$</span>m,<span class="at">xlab=</span><span class="st">"Nilai PDRB"</span>,<span class="at">ylab=</span><span class="st">"error"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/Nilai%20PDRB%20Jawa%20Timur-Error-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Plot pengaruh error terhadap nilai PDRB</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Teknik analisis yang digunakan dalam penelitian ini adalah teknik kuantitatif deskriptif. Metode yang dipilih adalah regresi multivariat dengan 2 variabel independen yaitu ekspor dan impor dan 1 variabel dependen yaitu PDRB. Penelitian ini bertujuan untuk mencari hubungan antara ekspor (X) dan impor (S) dengan PDRB (Y). Spesifikasi yang dilakukan adalah:</p>
<p><span class="math display">\[
Y=\beta_0 + \beta_1X+\beta_2S+\mu
\]</span> Di mana <span class="math inline">\(y_t\)</span> adalah hwy dan <span class="math inline">\(x_t\)</span> adalah cty. Di mana Y adalah PDRB Jawa Timur dan X adalah nilai ekspor Jawa Timur dan S adalah nilai impor Jawa Timur.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<table class="table">
<thead>
<tr class="header">
<th>Variabel</th>
<th>Coefficient</th>
<th>Std.Error</th>
<th>t-value</th>
<th>Prob (.)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intecerpt</td>
<td>4.733e+10</td>
<td>2.844e+10</td>
<td>1.664</td>
<td>0.1243</td>
</tr>
<tr class="even">
<td>X</td>
<td>7.293e+00</td>
<td>3.467e+00</td>
<td>2.104</td>
<td>0.0592</td>
</tr>
<tr class="odd">
<td>R squared</td>
<td>0.4038</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Adjusted R-Squared</td>
<td>0.2954</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>F-Statistic</td>
<td>3.725</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Prob(F-statistic)</td>
<td>0.05815</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>Hasil regresi yang telah didapat dimasukan ke dalam rumus persamaan yang ada sehingga menjadi:</p>
<p><span class="math display">\[
Y= 4.733 + 7.294 X+(-2.97 S)
\]</span></p>
<p>Ekspor pada pertumbuhan ekonomi berperan dalam peningkatan pertumbuhan ekonomi pada PDRB dikarenakan nilai variabel X yang positif, tetapi jika dilihat pada hasil regresinya ekspor tidak sepenuhnya mempengaruhi PDRB di Jawa Timur atau dalam arti lain peningkatan PDRB bukan hanya dipengaruhi ekspor saja tetapi terdapat faktor lain. Impor pada pertumbuhan ekonomi berbanding terbalik dengan ekspor, impor berpengaruh negatif terhadap PDRB Jawa Timur dikarenakan nilainya yang negatif, tetapi impor juga tidak sepenuhnya mempengaruhi PDRB. Jika diasumsikan setiap kenaikan nilai ekspor 1, maka PDRB akan meningkat sebesar 7.294. Tetapi jika diasumsikan nilai impor 1, maka PDRB akan ada penurunan sebesar 2.971.</p>
<p>Nilai Adjusted R-squared sebesar 0.2954 menjelaskan bahwa variabel independen di dalam penelitian ini dapat menjelaskan variasi variabel dependen sebesar 29,54 persen. Nilai F-statistik sebesar 3.725 menunjukkan bahwa variabel independen dalam jangka panjang seperti ekspor, impor berpengaruh secara bersama-sama terhadap tingkat pertumbuhan ekonomi atau terhadap PDRB.</p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil regresinya adalah</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>Hizkia<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'latihan.xlsx'</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X<span class="sc">+</span>S,<span class="at">data=</span>Hizkia)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X + S, data = Hizkia)

Residuals:
       Min         1Q     Median         3Q        Max 
-4.639e+10 -1.858e+10  9.087e+08  2.445e+10  4.861e+10 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)  4.733e+10  2.844e+10   1.664   0.1243  
X            7.293e+00  3.467e+00   2.104   0.0592 .
S           -2.971e+00  2.844e+00  -1.045   0.3186  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.21e+10 on 11 degrees of freedom
Multiple R-squared:  0.4038,    Adjusted R-squared:  0.2954 
F-statistic: 3.725 on 2 and 11 DF,  p-value: 0.05815</code></pre>
</div>
</div>
<p>Setiap kenaikan nilai ekspor dengan diasumsikan nilainya 1, maka dapat meningkatkan PDRB sebesar 7.293 dengan S yang sama,tetapi nilai impor berpengaruh negatif pada PDRB Jawa Timur, jika diasumsikan nilai impor 1 maka PDRB akan ada penurunan 2.971.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Setelah dilakukan penelitian melalui sistem regresi multivariat, maka dapat disimpulkan antara lain:</p>
<ol type="1">
<li>Nilai ekspor tidak sepenuhnya berpengaruh terhadap PDRB, tetapi nilai ekspor mempunyai nilai positif terhadap pertumbuhan PDRB hal ini sesuai dengan teori perdagangan internasional, apabila jumlah barang atau jasa yang di ekspor ke luar negeri semakin banyak maka di dalam negeri harus memproduksi barang dan jasa lebih banyak juga. Semakin banyak barang yang di ekspor ke luar negeri maka arus modal yang masuk ke dalam negeri juga dalam jumlah yang banyak.</li>
</ol>
<!-- -->
<ol start="2" type="1">
<li>Nilai impor memiliki efek negatif terhadap PDRB, dikarenakan apabila impor dilakukan melebihi ekspornya maka akan terjadi defisit ekspor yang memungkinkan untuk menurunkan PDRB. Sehingga sebaiknya setiap daerah untuk tidak berlebihan dalam melakukan kegiatan impor, agar dapat tercapai suatu surplus ekspor yang berakibat pada pertumbuhan ekonomi didaerah tersebut.</li>
</ol>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>Affandi, A., &amp; Gunawan, E. (2018). PENGARUH EKSPOR, IMPOR DAN JUMLAH PENDUDUK TERHADAP PDB INDONESIA TAHUN 1969 -2016. <em>Jurnal Perspektif Ekonomi Darussalam (Darussalam Journal of Economic Perspec</em>, 4(2), Article 2. https://doi.org/10.21157/j.ked.hewan.v%vi%i.13021</p>
<p>Nofinawati, N., Lubis, N. I., &amp; Nasution, J. (2017). PENGARUH EKSPOR DAN IMPOR TERHADAP PRODUK DOMESTIK REGIONAL BRUTO (PDRB) PROVINSI SUMATERA UTARA TAHUN 2008-2015. <em>Al-Masharif: Jurnal Ilmu Ekonomi Dan Keislaman</em>, 5(1), Article1. https://doi.org/10.24952/masharif.v5i1.1415</p>
<p>Hodijah, S., &amp; Angelina, G. P. (2021). ANALISIS PENGARUH EKSPOR DAN IMPOR TERHADAP PERTUMBUHAN EKONOMI DI INDONESIA. <em>Jurnal Manajemen Terapan Dan Keuangan</em>, 10(01), Article 01. https://doi.org/10.22437/jmk.v10i01.12512</p>
<p>Ginting, A. M. (2017). ANALISIS PENGARUH EKSPOR TERHADAP PERTUMBUHAN EKONOMI INDONESIA. <em>Buletin Ilmiah Litbang Perdagangan</em>, 11(1), Article 1. https://doi.org/10.30908/bilp.v11i1.185</p>
<p>Kisnawati, B., Irianto, I., &amp; Amrul, R. (2022). ANALISIS EKSPOR DAN IMPOR DALAM MENINGKATKAN PRODUK DOMESTIK REGIONAL BRUTO (PDRB) DI PROVINSI NUSA TENGGARA BARAT. <em>Nusantara Hasana Journal</em>, 2(2), Article 2.</p>
<p>1<em>55/PMK.04/2022 tentang Ketentuan Kepabeanan di Bidang Ekspor</em>. (n.d.).</p>
<p><em>View of Pengaruh Ekspor dan Impor terhadap Pertumbuhan Ekonomi di Provinsi Aceh</em>. (n.d.). Retrieved January 19, 2023, from https://journal.arraniry.ac.id/index.php/JIBES/article/view/1771/932</p>
<p><em>Pengertian Ekspor</em> | <em>hestanto</em>. (n.d.). Retrieved January 19, 2023, from https://www.hestanto.web.id/ekspor/</p>
<p><em>Multivariat &amp; Dummy regression</em>. (n.d.). Retrieved January 19, 2023, from https://www.krisna.or.id/metopel/meeting3/index.html#/bandingkan-2-model</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>